const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://th.bing.com/th/id/OIP.udb_ukkqhnGlLTG1aCr_0QHaEK?rs=1&pid=ImgDetMain?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ Kyekyeku-Tech" 


global.devs = "233545454000" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "233545454000";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGE || process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "recording" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923xxxxxxx,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_00_57_05_19_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICA0LFxuICAgICAgICAyMDgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTkxLFxuICAgICAgICAyNDcsXG4gICAgICAgIDYyLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMDQsXG4gICAgICAgIDgwLFxuICAgICAgICAxNTEsXG4gICAgICAgIDc1LFxuICAgICAgICAxODgsXG4gICAgICAgIDIyNixcbiAgICAgICAgNjUsXG4gICAgICAgIDkxLFxuICAgICAgICAxODIsXG4gICAgICAgIDcxLFxuICAgICAgICAyMDQsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTYyLFxuICAgICAgICA0LFxuICAgICAgICAxMDQsXG4gICAgICAgIDU1LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTk5LFxuICAgICAgICA0LFxuICAgICAgICAxNCxcbiAgICAgICAgODlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDYsXG4gICAgICAgIDExNixcbiAgICAgICAgMTcyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDYwLFxuICAgICAgICAzNSxcbiAgICAgICAgMjM4LFxuICAgICAgICA2NyxcbiAgICAgICAgODUsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTg5LFxuICAgICAgICA1NSxcbiAgICAgICAgMTQsXG4gICAgICAgIDIzOSxcbiAgICAgICAgNjIsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTY3LFxuICAgICAgICAxNTcsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMDksXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTkxLFxuICAgICAgICA1MCxcbiAgICAgICAgMTAxLFxuICAgICAgICAzMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgODMsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTM0LFxuICAgICAgICA2NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICAyMDMsXG4gICAgICAgIDY2LFxuICAgICAgICA5MCxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMTgsXG4gICAgICAgIDIyNSxcbiAgICAgICAgODUsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNDAsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTkwLFxuICAgICAgICAyNDAsXG4gICAgICAgIDQ5LFxuICAgICAgICAxMTQsXG4gICAgICAgIDI0LFxuICAgICAgICA2NSxcbiAgICAgICAgOSxcbiAgICAgICAgMTExLFxuICAgICAgICAxMjYsXG4gICAgICAgIDExMyxcbiAgICAgICAgNDAsXG4gICAgICAgIDEsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMTMsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjAzLFxuICAgICAgICA0OSxcbiAgICAgICAgMTE0LFxuICAgICAgICAyMTIsXG4gICAgICAgIDczXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1MyxcbiAgICAgICAgMjEsXG4gICAgICAgIDM5LFxuICAgICAgICAxNyxcbiAgICAgICAgMjE4LFxuICAgICAgICAxMjksXG4gICAgICAgIDE3NyxcbiAgICAgICAgNDcsXG4gICAgICAgIDM0LFxuICAgICAgICAxMTcsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTU1LFxuICAgICAgICA2MyxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNzAsXG4gICAgICAgIDk5LFxuICAgICAgICA5NCxcbiAgICAgICAgMTUyLFxuICAgICAgICA1OCxcbiAgICAgICAgMjQ5LFxuICAgICAgICA1MCxcbiAgICAgICAgMTE2LFxuICAgICAgICAyNTAsXG4gICAgICAgIDczLFxuICAgICAgICA3NCxcbiAgICAgICAgNzQsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTU5LFxuICAgICAgICAyMjQsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxMTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0OCxcbiAgICAgICAgMzAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTMsXG4gICAgICAgIDEyLFxuICAgICAgICAyNDIsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTM3LFxuICAgICAgICA2NyxcbiAgICAgICAgMjI1LFxuICAgICAgICAxNjAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTIsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTI5LFxuICAgICAgICA0OSxcbiAgICAgICAgOTQsXG4gICAgICAgIDIzOSxcbiAgICAgICAgNzUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMTEsXG4gICAgICAgIDY3LFxuICAgICAgICAxNDIsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTkwLFxuICAgICAgICAyNyxcbiAgICAgICAgMTcxLFxuICAgICAgICA0MixcbiAgICAgICAgMTg0LFxuICAgICAgICA1MSxcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTksXG4gICAgICAgIDgsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTExLFxuICAgICAgICAxMDksXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTIsXG4gICAgICAgIDQ1LFxuICAgICAgICAxOTQsXG4gICAgICAgIDc2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMzIsXG4gICAgICAgIDE3LFxuICAgICAgICAxMDYsXG4gICAgICAgIDQ3LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE3NyxcbiAgICAgICAgNzksXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjEwLFxuICAgICAgICAyOCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxODUsXG4gICAgICAgIDEyOSxcbiAgICAgICAgOTQsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTIsXG4gICAgICAgIDU2LFxuICAgICAgICAxODMsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDgsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgODksXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDEwMVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICAzNixcbiAgICAgICAgICA4MCxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDEyNVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE5NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjA5LFxuICAgICAgICAxNCxcbiAgICAgICAgNTEsXG4gICAgICAgIDYsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMTAsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTQ1LFxuICAgICAgICAxOTQsXG4gICAgICAgIDEyLFxuICAgICAgICA1OSxcbiAgICAgICAgMTEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTI2LFxuICAgICAgICA3NSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAwLFxuICAgICAgICAyMzMsXG4gICAgICAgIDQ0LFxuICAgICAgICA3LFxuICAgICAgICAxNixcbiAgICAgICAgMjM4LFxuICAgICAgICAxMDMsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTQsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMjMzLFxuICAgICAgICAxMTUsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjE2LFxuICAgICAgICA4OSxcbiAgICAgICAgMjM4LFxuICAgICAgICAxNDAsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTY2LFxuICAgICAgICAyMzEsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMzcsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNDYsXG4gICAgICAgIDE0OSxcbiAgICAgICAgNzAsXG4gICAgICAgIDI0LFxuICAgICAgICAxMjIsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTk4LFxuICAgICAgICAxOTgsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMzAsXG4gICAgICAgIDUwLFxuICAgICAgICAxNDcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTM5LFxuICAgICAgICA3OCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxMDEsXG4gICAgICAgIDE0MFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogODYsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwid0E2T3NOdnFOZ2RUUCsyQVV3RjRPVGYyQkNoUituVGhVMTdjN2dLaDUyWT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzM1NDU0NTQwMDBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjAwQTUxQURGQTE3MkQwMUU2NjYwNEYwQzhEOTAxQ0ZDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNjA4MDI1NFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJ2VDlzcjdOa1E3aTVKU0NwVGNvZURBXCIsXG4gIFwicGhvbmVJZFwiOiBcImI5NmE1ZWZkLTZmOGQtNDM0MS05NTZmLTI5YjZkZTIxNDBhN1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA2LFxuICAgICAgNTAsXG4gICAgICAxNTQsXG4gICAgICAyNTEsXG4gICAgICAxMjQsXG4gICAgICAyNDcsXG4gICAgICAxMjcsXG4gICAgICAxODAsXG4gICAgICAyMDIsXG4gICAgICAxNDUsXG4gICAgICAxNDksXG4gICAgICAxNjMsXG4gICAgICAxNzUsXG4gICAgICA4NSxcbiAgICAgIDQ4LFxuICAgICAgMTM3LFxuICAgICAgMjAzLFxuICAgICAgMTAxLFxuICAgICAgMTM5LFxuICAgICAgMjA2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMjUsXG4gICAgICAxNDMsXG4gICAgICAxNjksXG4gICAgICAzNCxcbiAgICAgIDk1LFxuICAgICAgMzEsXG4gICAgICAyOSxcbiAgICAgIDU4LFxuICAgICAgMTIxLFxuICAgICAgMTUwLFxuICAgICAgMTgxLFxuICAgICAgNTAsXG4gICAgICAyMzMsXG4gICAgICAxMDIsXG4gICAgICAxMzQsXG4gICAgICAyNTMsXG4gICAgICAyMjEsXG4gICAgICAyNSxcbiAgICAgIDE2OCxcbiAgICAgIDIzNFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0pLLzJQWUVFUFNjcGJJR0dBZ2dBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiQjhpMHNzbVdUS3Q3Z3RmYWJlVFZQMEtmZmx4NUVNMm9VZ29nUE4yRk1nND1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCI5d29sODh4ZGJIVTRBcXFRZVV3OHZybWhrcGpyeDZ6NDZRdDhnODRZbG9aQjlPRE9IRnlXcitSVWlIZzBtUSsyT2pPaEQ1aTA4UHVHY01ud0UzL3NBdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJvazZuR3g4b09QT0RrV3lVVnJjUFVVZ0JNbDFKbGdJV0lMTytncjJyRnl0Tlltc0VjOG41QVpZOTJQSmhKUzgxMnF5RDNDQ2Y5MXpZQW9YNWFHSm5qQT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzMzU0NTQ1NDAwMDoxMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIktZRUtZRUtVIFRFQ0hcIixcbiAgICBcImxpZFwiOiBcIjMxMjIwNTcwMjY3ODkwOjEwQGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjMzNTQ1NDU0MDAwOjEwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICA5MixcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAzMixcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDE0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTYwODAyNDgsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFLUGJcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtQVi5qc29uIjogIntcImtleURhdGFcIjpcIkJOVnJ1R3FkZ3AzNDAwUTk3aGRmNXcrZUdRWm5rMHVCaWJQZ3RtWkx4a3c9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTMyMjY1NTYzNCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzEyMjQyODE1NjYwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS1BXLmpzb24iOiAie1wia2V5RGF0YVwiOlwiR1JUWVBFc2hPbitXVmlwNzNZR2ZyYjRvSitiTHp0Yy9wTXdpYTFrcmZkdz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzIyNjU1NjM0LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxLDJdfSxcInRpbWVzdGFtcFwiOlwiMTcxNDgzNjM0NzcyMVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtQWC5qc29uIjogIntcImtleURhdGFcIjpcInhzRndjaHlIMStBYmlITXkzeUJkTXMzaE4yT1VhcFo0d1R6QTFic0VsdTg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTMyMjY1NTYzNCxcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSwyXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLUFkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJTT0MzV0oxR0kzMHRpaXJ1eFpQZElXc1VzSEJMaW1UN0JZbzc4b2lleUZJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzMjI2NTU2MzQsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS1BaLmpzb24iOiAie1wia2V5RGF0YVwiOlwiL3ptVWphaXFUQTdvNWxkZjRlaUFOWnRNWW9pRmJ2bG43MXVWN1FaRklmRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzIyNjU1NjM0LFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLUGEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJjZ0RkaGZOeEREaC9ZL2tUaXhVTEdOWVpWdVkwQkZIdTNMM2Z3SjBHUnZBPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzMjI2NTU2MzQsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtQYi5qc29uIjogIntcImtleURhdGFcIjpcIll2SkNtaVNrTzB1dzFleHBWYkxIaUlqU3hqSEljWjEvMlpmazc3OThscGc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTMyMjY1NTYzNCxcImN1cnJlbnRJbmRleFwiOjcsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSw3XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLUGMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJWRkJldzh5cUg2L0RUeFhoN25kc0I5aU1FeTRLRDhCRWFQekFBTHBxZHUwPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzMjI2NTU2MzQsXCJjdXJyZW50SW5kZXhcIjo3LFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxNjA4MDIxMTYwM1wifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.4",
  caption : global.caption || "『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ KYEKYEKU-TECH 』" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "KYEKYEKU",
  ownername:process.env.OWNER_NAME|| "It'x Oppong Safo",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "HRKU-e4313cbf-b242-483c-99f5-1cf68a3009b8",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "daniel1",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SAFO"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
